/*=====================================================
  dbo.USERS - Security Columns
  Re-runnable Script
=====================================================*/

-- PASSWORDHASH
IF COL_LENGTH('dbo.USERS', 'PASSWORDHASH') IS NULL
BEGIN
    ALTER TABLE dbo.USERS
    ADD PASSWORDHASH NVARCHAR(1000) NULL;
END
GO

-- PASSWORDMIGRATED
IF COL_LENGTH('dbo.USERS', 'PASSWORDMIGRATED') IS NULL
BEGIN
    ALTER TABLE dbo.USERS
    ADD PASSWORDMIGRATED BIT NOT NULL
        CONSTRAINT DF_USERS_PASSWORDMIGRATED DEFAULT(0);
END
GO

-- LASTLOGINAT
IF COL_LENGTH('dbo.USERS', 'LASTLOGINAT') IS NULL
BEGIN
    ALTER TABLE dbo.USERS
    ADD LASTLOGINAT DATETIME2 NULL;
END
GO

-- PASSWORDRESETREQUIRED
IF COL_LENGTH('dbo.USERS', 'PASSWORDRESETREQUIRED') IS NULL
BEGIN
    ALTER TABLE dbo.USERS
    ADD PASSWORDRESETREQUIRED BIT NOT NULL
        CONSTRAINT DF_USERS_PASSWORDRESETREQUIRED DEFAULT(0);
END
GO

-- UPDATEDAT
IF COL_LENGTH('dbo.USERS', 'UPDATEDAT') IS NULL
BEGIN
    ALTER TABLE dbo.USERS
    ADD UPDATEDAT DATETIME2 NULL;
END
GO