/*
    Creates mapping table between supplier users and transport users.

    Supplier source:
      dbo.USERS(USERID), where supplier users are ROLE = 1 in application logic.

    Transport source:
      dbo.USERS(USERID), where transport users are ROLE = 2 in application logic.
*/

IF OBJECT_ID(N'dbo.SUPPLIERTRANSPORTMAPPING', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.SUPPLIERTRANSPORTMAPPING
    (
        ID INT IDENTITY(1,1) NOT NULL,
        SUPPLIERUSERID INT NOT NULL,
        TRANSPORTID INT NOT NULL,
        CONSTRAINT PK_SUPPLIERTRANSPORTMAPPING
            PRIMARY KEY CLUSTERED (ID)
    );
END;
GO

IF COL_LENGTH('dbo.SUPPLIERTRANSPORTMAPPING', 'SUPPLIERUSERID') IS NULL
BEGIN
    ALTER TABLE dbo.SUPPLIERTRANSPORTMAPPING
        ADD SUPPLIERUSERID INT NOT NULL;
END;
GO

IF COL_LENGTH('dbo.SUPPLIERTRANSPORTMAPPING', 'TRANSPORTID') IS NULL
BEGIN
    ALTER TABLE dbo.SUPPLIERTRANSPORTMAPPING
        ADD TRANSPORTID INT NOT NULL;
END;
GO

IF NOT EXISTS
(
    SELECT 1
    FROM sys.foreign_keys
    WHERE name = 'FK_SUPPLIERTRANSPORTMAPPING_SUPPLIER_USERS'
      AND parent_object_id = OBJECT_ID(N'dbo.SUPPLIERTRANSPORTMAPPING')
)
BEGIN
    ALTER TABLE dbo.SUPPLIERTRANSPORTMAPPING
        ADD CONSTRAINT FK_SUPPLIERTRANSPORTMAPPING_SUPPLIER_USERS
            FOREIGN KEY (SUPPLIERUSERID)
            REFERENCES dbo.USERS (USERID);
END;
GO

IF NOT EXISTS
(
    SELECT 1
    FROM sys.foreign_keys
    WHERE name = 'FK_SUPPLIERTRANSPORTMAPPING_TRANSPORT_USERS'
      AND parent_object_id = OBJECT_ID(N'dbo.SUPPLIERTRANSPORTMAPPING')
)
BEGIN
    ALTER TABLE dbo.SUPPLIERTRANSPORTMAPPING
        ADD CONSTRAINT FK_SUPPLIERTRANSPORTMAPPING_TRANSPORT_USERS
            FOREIGN KEY (TRANSPORTID)
            REFERENCES dbo.USERS (USERID);
END;
GO

IF NOT EXISTS
(
    SELECT 1
    FROM sys.indexes
    WHERE name = 'UX_SUPPLIERTRANSPORTMAPPING_SUPPLIERUSERID_TRANSPORTID'
      AND object_id = OBJECT_ID(N'dbo.SUPPLIERTRANSPORTMAPPING')
)
BEGIN
    CREATE UNIQUE INDEX UX_SUPPLIERTRANSPORTMAPPING_SUPPLIERUSERID_TRANSPORTID
        ON dbo.SUPPLIERTRANSPORTMAPPING (SUPPLIERUSERID, TRANSPORTID);
END;
GO

IF NOT EXISTS
(
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_SUPPLIERTRANSPORTMAPPING_TRANSPORTID'
      AND object_id = OBJECT_ID(N'dbo.SUPPLIERTRANSPORTMAPPING')
)
BEGIN
    CREATE INDEX IX_SUPPLIERTRANSPORTMAPPING_TRANSPORTID
        ON dbo.SUPPLIERTRANSPORTMAPPING (TRANSPORTID);
END;
GO
