IF COL_LENGTH('dbo.PRODUCTS', 'IsGSTRule') IS NULL
BEGIN
    ALTER TABLE dbo.PRODUCTS
    ADD IsGSTRule BIT NOT NULL
        CONSTRAINT DF_PRODUCTS_IsGSTRule DEFAULT (0);
END
GO

IF COL_LENGTH('dbo.PRODUCTS', 'IsAdditionalCharges') IS NULL
BEGIN
    ALTER TABLE dbo.PRODUCTS
    ADD IsAdditionalCharges BIT NOT NULL
        CONSTRAINT DF_PRODUCTS_IsAdditionalCharges DEFAULT (0);
END
GO